### ISSUE TITLE
UWA MEG FISHERIES - 

### ISSUE THREAD

**Issue by TimLanglois** [UWAMEGFisheries/UWAMEGFisheries.github.io#7]
@BrookeGibbons  can the top left title be expanded maybe onto two lines so it reads.
"UWA Marine Ecology Group - Fisheries"

**Comment by BrookeGibbons** [comment]
@TimLanglois I've changed the title. It looks a bit weird don't you think?

**Comment by BrookeGibbons** [comment]
@TimLanglois I've made a workaround (with powerpoint), do you think we need UWA in the title?
